name: mono_cli
description: CLI exports and implementations for the Mono CLI, used by the mono package.
resolution: workspace
version: 0.0.7
homepage: https://github.com/jozzdart/mono
repository: https://github.com/jozzdart/mono/tree/main/mono_cli
issue_tracker: https://github.com/jozzdart/mono/issues
topics:
  - mono
  - monorepo
  - cli
  - tool

environment:
  sdk: ">=3.5.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dependencies:
  mono_core: ^0.0.7
  args: ^2.5.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.9.0
  pool: ^1.5.2

dev_dependencies:
  lints:
  test:
