name: mono_workspace
description: Mono Workspace
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - mono
  - mono_cli
  - mono_core

dependencies:
  args: ^2.5.0
  yaml: ^3.1.2
  glob: ^2.1.2
  path: ^1.9.0
  pool: ^1.5.2

dev_dependencies:
  test: ^1.26.1
  lints: ^5.1.1
