name: mono_workspace
description: Mono Workspace
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

workspace:
  - mono
  - mono_cli
  - mono_core

dependencies:

dev_dependencies:
  test: ^1.26.1
  lints: ^6.0.0
