name: mono_config_contracts
description: "Config model and validation contracts for Mono"
resolution: workspace
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta:
  mono_core_types:
  mono_selector_contracts:

dev_dependencies:
  test:
  lints:
