name: mono_graph_builder_impl
description: GraphBuilder implementation for mono CLI.
resolution: workspace
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta:
  mono_ports:
  mono_core_types:
  mono_graph_contracts:

dev_dependencies:
  lints:
  test:
