name: mono_scanner_fs
description: Filesystem-based PackageScanner implementation for mono CLI.
version: 0.1.0
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta:
  yaml:
  glob:
  path:
  mono_ports:
  mono_core_types:

dev_dependencies:
  lints:
  test:
