# tasks:
build:
  plugin: exec
  run:
    - dart run build_runner build --delete-conflicting-outputs

publishdry:
  plugin: exec
  run:
    - dart pub publish --dry-run

publishyes:
  plugin: exec
  run:
    - dart pub publish --force

format:
  plugin: exec
  run:
    - dart format .
