name: mono_selector_contracts
description: "Target selection AST contracts for Mono (contracts-only)"
resolution: workspace
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta:
  mono_core_types:

dev_dependencies:
  test:
  lints:
