name: mono_core
description: "Mono Core"
resolution: workspace
version: 0.0.1
homepage:
publish_to: "none"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  mono_core_types:
  mono_graph_contracts:
  mono_selector_contracts:

dev_dependencies:
  test:
  lints:
