name: mono
description: The fastest and most flexible CLI for managing Dart/Flutter monorepos, tasks, scanning, groups, and more.
resolution: workspace
version: 0.0.7
homepage: https://github.com/jozzdart/mono
repository: https://github.com/jozzdart/mono/tree/main/mono
issue_tracker: https://github.com/jozzdart/mono/issues
topics:
  - mono
  - monorepo
  - cli
  - tool

environment:
  sdk: ">=3.5.0 <4.0.0"

platforms:
  linux:
  macos:
  windows:

dependencies:
  mono_cli: ^0.0.7
  mono_core: ^0.0.7

dev_dependencies:
  lints:
  test:
  path:

executables:
  mono: mono
